spring.application.name=SeCrud

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/movie_booking
spring.datasource.username=root
spring.datasource.password=oS@20041221
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# This will show the SQL commands being executed
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR

# Enable stacktrace in error responses (useful for local debugging)
server.error.include-stacktrace=always
# Increase logging for web requests and JSP compilation
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.jasper=DEBUG

